SELECT QUERY_DOC_ID,
       COUNT,
       CURR_TIME,
       FINISH_FLAG
  FROM KPDBA.COURSE_QUERY_DOCUMENT
 WHERE COURSE_DOC_ID = :AS_COURSE_DOC_ID AND QUERY_ID = :AS_QUERY_ID AND APP_EMP_ID =:AS_APP_EMP_ID