SELECT TOPIC_ID,
       CDM.COURSE_DOC_ID,
       DOC_ORDER,
       DOC_TYPE,
       DOC_NAME,
       DOC_PATH,
       VIDEO_COVER,
       VIDEO_LENGTH
  FROM (SELECT TOPIC_ID, COURSE_DOC_ID, DOC_ORDER FROM KPDBA.TOPIC_DOCUMENT) TD,
       (SELECT COURSE_DOC_ID,
               DOC_TYPE,
               DOC_NAME,
               DOC_PATH,
               VIDEO_COVER,
               VIDEO_LENGTH
          FROM KPDBA.COURSE_DOCUMENT_MASTER
         WHERE CANCEL_FLAG = 'F') CDM
 WHERE TD.COURSE_DOC_ID = CDM.COURSE_DOC_ID AND TD.TOPIC_ID = :AD_TOPIC_ID ORDER BY DOC_ORDER ASC