SELECT TOPIC_ID,
       TOPIC_ORDER,
       TOPIC_NAME,
       PARENT_TOPIC_ID GROUP_ID
  FROM KPDBA.TOPIC_MASTER
 WHERE     PARENT_TOPIC_ID = :AD_PARENT_TOPIC_ID
       AND TOPIC_TYPE = 'T'
       AND CANCEL_FLAG = 'F' ORDER BY TOPIC_ORDER ASC