INSERT INTO KPDBA.COLOR_FOLDER (CF_SEQ,
                                PROD_ID,
                                REVISION,
                                CR_QTY,
                                COLLECTION_DATE,
                                CR_DATE,
                                CR_ORG_ID,
                                CF_TYPE,
                                JOB_ID,
                                CUST_ID,
                                CR_USER_ID)
     VALUES (:AS_CF_SEQ,
             :AS_PROD_ID,
             :AS_REVISION,
             TO_NUMBER (:AS_CR_QTY),
             TO_DATE (:AS_COLLECTION_DATE, 'yyyy-mm-dd'),
             SYSDATE,
             TO_CHAR (:AS_CR_ORG_ID),
             :AS_CF_TYPE,
             :AS_JOB_ID,
             :AS_CUST_ID,
             TO_CHAR (:AS_CR_USER_ID))