  SELECT C.CUST_NAME, C.CUST_ID, DECODE (P.CUST_ID, NULL, 'Z', 'A') ORD
    FROM    KPDBA.CUSTOMER C
         LEFT JOIN
            (SELECT P.CUST_ID
               FROM KPDBA.PROD_CUST P
              WHERE P.PROD_ID = :AS_PROD_ID AND P.REVISION = :AS_REVISION) P
         ON C.CUST_ID = P.CUST_ID
   WHERE C.CANCEL_FLAG = 'F'
ORDER BY DECODE (P.CUST_ID, NULL, 'Z', 'A'), C.CUST_NAME