  SELECT DISTINCT J.JOB_ID, C.CUST_ID, C.CUST_NAME
    FROM KPDBA.JOB J
         JOIN KPDBA.JOB_DETAIL JD
            ON J.JOB_ID = JD.JOB_ID
         JOIN KPDBA.CUSTOMER C
            ON C.CUST_ID = J.CUST_ID
   WHERE     J.STATUS <> 'C'
         AND JD.PROD_ID = :AS_PROD_ID
         AND JD.REVISION = :AS_REVISION
ORDER BY J.JOB_ID ASC