SELECT SN.CF_SN,
       C.CUST_NAME,
       P.PROD_ID,
       P.PROD_DESC,
       TRUNC (CF.RETURN_DATE) APP_DATE,
       CF.EXPIRE_DATE,
       CASE
          WHEN SN.CF_NO IS NULL THEN NULL
          ELSE TO_CHAR (SN.CF_NO) || '/' || TO_CHAR (CF.SUBMIT_QTY)
       END
          RUNNING_NO,
       ' ' APPROVAL,
       SN.CF_SEQ
  FROM KPDBA.COLOR_FOLDER CF
       JOIN KPDBA.COLOR_FOLDER_SN SN
          ON CF.CF_SEQ = SN.CF_SEQ
       JOIN KPDBA.PRODUCT P
          ON CF.PROD_ID = P.PROD_ID AND CF.REVISION = P.REVISION
       LEFT JOIN KPDBA.CUSTOMER C
          ON CF.CUST_ID = C.CUST_ID
 WHERE SN.CF_STATUS != 'CNCL' AND CF.CF_SEQ = :AS_CF_SEQ