  SELECT C.CUST_NAME,
         P.PROD_ID,
         P.PROD_DESC,
         TRUNC (CF.RETURN_DATE) APP_DATE,
         CF.EXPIRE_DATE,
         TO_CHAR (SN.CF_NO) || '/' || TO_CHAR (CF.SUBMIT_QTY) RUNNING_NO,
         ' ' APPROVAL,
         SN.CF_SN
    FROM KPDBA.COLOR_FOLDER CF
         JOIN KPDBA.COLOR_FOLDER_SN SN
            ON CF.CF_SEQ = SN.CF_SEQ
         JOIN KPDBA.PRODUCT P
            ON CF.PROD_ID = P.PROD_ID AND CF.REVISION = P.REVISION
         JOIN KPDBA.PROD_CUST PC
            ON CF.PROD_ID = PC.PROD_ID AND CF.REVISION = PC.REVISION
         JOIN KPDBA.CUSTOMER C
            ON PC.CUST_ID = C.CUST_ID
   WHERE     (   PROD_DESC LIKE '%' || :AS_TXT_SEARCH || '%'
              OR CF.PROD_ID LIKE '%' || :AS_TXT_SEARCH || '%')
         AND CF.CANCEL_FLAG = 'F'
         AND ROWNUM <= 25
ORDER BY RUNNING_NO ASC