  SELECT CF_REJ_REASON, CF_REJ_REASON_DESC
    FROM KPDBA.CF_REJECT_MASTER
   WHERE     CANCEL_FLAG = 'F'
         AND CF_REJ_REASON_DESC LIKE '%' || :AS_TXT_SEARCH || '%'
ORDER BY CF_REJ_REASON_DESC ASC